### ISSUE TITLE
svg file impossible to edit in inkscape

### ISSUE THREAD

**Issue by BenjiSan** [meetdilip/gnome_folder_colour#1]
Hi! Thanks for the icons, I have a issue, I try to edit the svg to make individual folder icons but I cant, the big folder icon is attached with the littles ones. There is any way to solve this?

**Comment by meetdilip** [comment]
Which colour ?

**Comment by meetdilip** [comment]
You can try the attached file. To edit, " ungroup " respective icons. Otherwise, it will work as individual icons. All variants included


[folders_orange_individual.zip](https://github.com/meetdilip/gnome_folder_colour/files/5073930/folders_orange_individual.zip)

Respective license apply

https://gitlab.gnome.org/GNOME/adwaita-icon-theme

**Comment by BenjiSan** [comment]
> You can try the attached file. To edit, " ungroup " respective icons. Otherwise, it will work as individual icons. All variants included
> 
> [folders_orange_individual.zip](https://github.com/meetdilip/gnome_folder_colour/files/5073930/folders_orange_individual.zip)
> 
> Respective license apply
> 
> https://gitlab.gnome.org/GNOME/adwaita-icon-theme

The blue ones. I tried your suggestion but the icons lose the color scheme when I try to ungroup them. Maybe I'm doing something wrong. Thanks for your help.

This happen

![Captura de pantalla de 2020-08-14 05-15-27](https://user-images.githubusercontent.com/13210014/90239717-a09f3f00-dded-11ea-8323-c47c0fe33a56.png)

**Comment by meetdilip** [comment]
May I know what exactly you are trying to do ? You have almost the same files in  **folders_orange_individual.zip** in the attached file in post #3 of this issue. 

If you want a wider catalogue, you can use the orange base file in the repo. In that, there are only big folders. So you can make changes to it and resize to any dimension you like.

**Comment by BenjiSan** [comment]
I want to make each icon folder for my customized (personal) icon theme (I did some icons but in granny part they are from suru+ and papirus icon themes)... I recently switched to fedora and I use Adwaita icon theme but the default folder icons does not finish convincing me. I tried the folders_blue.svg because it has the icons in diferente sizes (the 16, 22, 24 px). Thanks

**Comment by meetdilip** [comment]
If you don't mind, it is quite easy to customise the Orange ones and then resize it. If you want to save the effort, I suggest you try some Inkscape commands through Terminal. That will be within the scope of Inkscape support. There is little I can do in suggestions about Inkscape workflow.

**Comment by meetdilip** [comment]
I just tried the blue base file. When ungrouped, it works fine for me. I am able to customise it easily

![github issue](https://user-images.githubusercontent.com/6965443/90304068-8fc7f980-ded1-11ea-95da-f2bef48e99bb.png)

I think you will to take some help from Inkscape support in this case. All good at this end as far as I can see.
